import type {
  Employee,
  Department,
  Attendance,
  Task,
  VacationRequest,
  DocumentRequest,
  Payroll,
  JobOffer,
  Candidate,
  DashboardStats,
  Notification,
} from '@/types';

export const mockDepartments: Department[] = [
  { id: '1', name: 'Human Resources', code: 'HR', organization_id: 'org-1', manager_id: null, parent_id: null, created_at: '2022-01-01' },
  { id: '2', name: 'Engineering', code: 'ENG', organization_id: 'org-1', manager_id: null, parent_id: null, created_at: '2022-01-01' },
  { id: '3', name: 'Sales', code: 'SAL', organization_id: 'org-1', manager_id: null, parent_id: null, created_at: '2022-01-01' },
  { id: '4', name: 'Marketing', code: 'MKT', organization_id: 'org-1', manager_id: null, parent_id: null, created_at: '2022-01-01' },
  { id: '5', name: 'Finance', code: 'FIN', organization_id: 'org-1', manager_id: null, parent_id: null, created_at: '2022-01-01' },
  { id: '6', name: 'Operations', code: 'OPS', organization_id: 'org-1', manager_id: null, parent_id: null, created_at: '2022-01-01' },
];

export const mockEmployees: Employee[] = [
  {
    id: '1',
    profile_id: '2',
    employee_code: 'EMP001',
    organization_id: 'org-1',
    hire_date: '2022-01-15',
    department_id: '1',
    position: 'HR Manager',
    contract_type: 'FULL_TIME',
    base_salary: 75000,
    cnss: 'CNSS123456',
    rib: '12345678901234567890',
    bank_name: 'Chase Bank',
    manager_id: null,
    created_at: '2022-01-15',
  },
  {
    id: '2',
    profile_id: '3',
    employee_code: 'EMP002',
    organization_id: 'org-1',
    hire_date: '2021-06-01',
    department_id: '2',
    position: 'Engineering Manager',
    contract_type: 'FULL_TIME',
    base_salary: 95000,
    cnss: 'CNSS234567',
    rib: '23456789012345678901',
    bank_name: 'Bank of America',
    manager_id: null,
    created_at: '2021-06-01',
  },
  {
    id: '3',
    profile_id: '4',
    employee_code: 'EMP003',
    organization_id: 'org-1',
    hire_date: '2023-03-10',
    department_id: '2',
    position: 'Software Developer',
    contract_type: 'FULL_TIME',
    base_salary: 65000,
    cnss: 'CNSS345678',
    rib: '34567890123456789012',
    bank_name: 'Wells Fargo',
    manager_id: '2',
    created_at: '2023-03-10',
  },
  {
    id: '4',
    profile_id: '5',
    employee_code: 'EMP004',
    organization_id: 'org-1',
    hire_date: '2022-09-20',
    department_id: '3',
    position: 'Sales Representative',
    contract_type: 'FULL_TIME',
    base_salary: 55000,
    cnss: 'CNSS456789',
    rib: '45678901234567890123',
    bank_name: 'Chase Bank',
    manager_id: null,
    created_at: '2022-09-20',
  },
  {
    id: '5',
    profile_id: '6',
    employee_code: 'EMP005',
    organization_id: 'org-1',
    hire_date: '2023-01-05',
    department_id: '4',
    position: 'Marketing Specialist',
    contract_type: 'FULL_TIME',
    base_salary: 58000,
    cnss: 'CNSS567890',
    rib: '56789012345678901234',
    bank_name: 'Citibank',
    manager_id: null,
    created_at: '2023-01-05',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: '1',
    employee_id: '1',
    date: new Date().toISOString().split('T')[0],
    check_in: '08:55:00',
    check_out: null,
    status: 'PRESENT',
    notes: null,
    work_hours: 0,
    overtime_hours: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    employee_id: '2',
    date: new Date().toISOString().split('T')[0],
    check_in: '09:15:00',
    check_out: null,
    status: 'LATE',
    notes: null,
    work_hours: 0,
    overtime_hours: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    employee_id: '3',
    date: new Date().toISOString().split('T')[0],
    check_in: '08:45:00',
    check_out: null,
    status: 'PRESENT',
    notes: null,
    work_hours: 0,
    overtime_hours: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    employee_id: '4',
    date: new Date().toISOString().split('T')[0],
    check_in: null,
    check_out: null,
    status: 'ON_LEAVE',
    notes: null,
    work_hours: 0,
    overtime_hours: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    employee_id: '5',
    date: new Date().toISOString().split('T')[0],
    check_in: '08:30:00',
    check_out: null,
    status: 'PRESENT',
    notes: null,
    work_hours: 0,
    overtime_hours: 0,
    created_at: new Date().toISOString(),
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Complete Q4 Performance Review',
    description: 'Review and submit performance evaluations for all team members',
    assigned_to: '3',
    assigned_by: '2',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    due_date: '2024-12-31',
    completed_at: null,
    performance_score: null,
    feedback: null,
    created_at: '2024-12-01',
  },
  {
    id: '2',
    title: 'Update Employee Handbook',
    description: 'Review and update the employee handbook with new policies',
    assigned_to: '1',
    assigned_by: '2',
    status: 'TODO',
    priority: 'MEDIUM',
    due_date: '2024-12-20',
    completed_at: null,
    performance_score: null,
    feedback: null,
    created_at: '2024-12-05',
  },
  {
    id: '3',
    title: 'Prepare Training Materials',
    description: 'Create onboarding materials for new hires',
    assigned_to: '3',
    assigned_by: '2',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    due_date: '2024-12-10',
    completed_at: '2024-12-08',
    performance_score: 95,
    feedback: 'Excellent work!',
    created_at: '2024-12-01',
  },
  {
    id: '4',
    title: 'Fix Bug in Payroll Module',
    description: 'Investigate and fix the overtime calculation bug',
    assigned_to: '3',
    assigned_by: '2',
    status: 'UNDER_REVIEW',
    priority: 'URGENT',
    due_date: '2024-12-15',
    completed_at: null,
    performance_score: null,
    feedback: null,
    created_at: '2024-12-10',
  },
];

export const mockVacationRequests: VacationRequest[] = [
  {
    id: '1',
    employee_id: '3',
    type: 'ANNUAL',
    start_date: '2024-12-23',
    end_date: '2024-12-27',
    days: 5,
    reason: 'Christmas vacation with family',
    status: 'APPROVED',
    approved_by: '2',
    approved_at: '2024-12-05',
    comments: null,
    created_at: '2024-12-01',
  },
  {
    id: '2',
    employee_id: '4',
    type: 'SICK',
    start_date: '2024-12-10',
    end_date: '2024-12-12',
    days: 3,
    reason: 'Medical appointment and recovery',
    status: 'PENDING',
    approved_by: null,
    approved_at: null,
    comments: null,
    created_at: '2024-12-09',
  },
  {
    id: '3',
    employee_id: '5',
    type: 'ANNUAL',
    start_date: '2025-01-15',
    end_date: '2025-01-20',
    days: 6,
    reason: 'Personal trip',
    status: 'PENDING',
    approved_by: null,
    approved_at: null,
    comments: null,
    created_at: '2024-12-10',
  },
];

export const mockDocumentRequests: DocumentRequest[] = [
  {
    id: '1',
    employee_id: '3',
    type: 'ATTESTATION',
    title: 'Employment Certificate',
    description: 'Need for visa application',
    status: 'READY',
    file_url: null,
    requested_at: '2024-12-01',
    completed_at: '2024-12-03',
    processed_by: '2',
  },
  {
    id: '2',
    employee_id: '4',
    type: 'PAYSLIP',
    title: 'November 2024 Payslip',
    description: 'For loan application',
    status: 'DELIVERED',
    file_url: null,
    requested_at: '2024-12-05',
    completed_at: '2024-12-06',
    processed_by: '2',
  },
  {
    id: '3',
    employee_id: '5',
    type: 'CERTIFICATE',
    title: 'Salary Certificate',
    description: 'For apartment rental',
    status: 'PENDING',
    file_url: null,
    requested_at: '2024-12-10',
    completed_at: null,
    processed_by: null,
  },
];

export const mockPayrolls: Payroll[] = [
  {
    id: '1',
    employee_id: '1',
    month: 11,
    year: 2024,
    base_salary: 75000,
    overtime_pay: 0,
    bonuses: 2000,
    deductions: 1500,
    tax_amount: 15000,
    net_salary: 60500,
    status: 'PAID',
    paid_at: '2024-11-30',
    payslip_url: null,
    created_at: '2024-11-25',
  },
  {
    id: '2',
    employee_id: '2',
    month: 11,
    year: 2024,
    base_salary: 95000,
    overtime_pay: 500,
    bonuses: 3000,
    deductions: 1000,
    tax_amount: 19500,
    net_salary: 78000,
    status: 'PAID',
    paid_at: '2024-11-30',
    payslip_url: null,
    created_at: '2024-11-25',
  },
  {
    id: '3',
    employee_id: '3',
    month: 11,
    year: 2024,
    base_salary: 65000,
    overtime_pay: 800,
    bonuses: 1000,
    deductions: 500,
    tax_amount: 13000,
    net_salary: 53300,
    status: 'PAID',
    paid_at: '2024-11-30',
    payslip_url: null,
    created_at: '2024-11-25',
  },
  {
    id: '4',
    employee_id: '1',
    month: 12,
    year: 2024,
    base_salary: 75000,
    overtime_pay: 0,
    bonuses: 5000,
    deductions: 1500,
    tax_amount: 15000,
    net_salary: 63500,
    status: 'PENDING',
    paid_at: null,
    payslip_url: null,
    created_at: '2024-12-25',
  },
];

export const mockJobOffers: JobOffer[] = [
  {
    id: '1',
    title: 'Senior Software Engineer',
    organization_id: 'org-1',
    department_id: '2',
    description: 'We are looking for an experienced software engineer to join our team...',
    requirements: '5+ years of experience with React and Node.js',
    location: 'San Francisco, CA (Hybrid)',
    type: 'FULL_TIME',
    salary_min: 120000,
    salary_max: 160000,
    status: 'PUBLISHED',
    published_at: '2024-12-01',
    closed_at: null,
    created_by: '2',
    created_at: '2024-11-25',
  },
  {
    id: '2',
    title: 'HR Specialist',
    organization_id: 'org-1',
    department_id: '1',
    description: 'Join our HR team to help manage employee relations...',
    requirements: '3+ years of HR experience',
    location: 'San Francisco, CA (On-site)',
    type: 'FULL_TIME',
    salary_min: 60000,
    salary_max: 80000,
    status: 'PUBLISHED',
    published_at: '2024-12-05',
    closed_at: null,
    created_by: '2',
    created_at: '2024-12-01',
  },
  {
    id: '3',
    title: 'Marketing Manager',
    organization_id: 'org-1',
    department_id: '4',
    description: 'Lead our marketing initiatives and drive growth...',
    requirements: '5+ years of marketing experience',
    location: 'Remote',
    type: 'FULL_TIME',
    salary_min: 90000,
    salary_max: 120000,
    status: 'CLOSED',
    published_at: '2024-11-01',
    closed_at: '2024-12-01',
    created_by: '2',
    created_at: '2024-10-25',
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    job_offer_id: '1',
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@email.com',
    phone: '+1 555-0101',
    cv_url: null,
    status: 'INTERVIEW',
    interview_date: '2024-12-15T14:00:00',
    notes: 'Strong technical background',
    created_at: '2024-12-01',
  },
  {
    id: '2',
    job_offer_id: '1',
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane.smith@email.com',
    phone: '+1 555-0102',
    cv_url: null,
    status: 'SCREENING',
    interview_date: null,
    notes: 'Good portfolio',
    created_at: '2024-12-03',
  },
  {
    id: '3',
    job_offer_id: '2',
    first_name: 'Michael',
    last_name: 'Johnson',
    email: 'michael.j@email.com',
    phone: '+1 555-0103',
    cv_url: null,
    status: 'NEW',
    interview_date: null,
    notes: null,
    created_at: '2024-12-10',
  },
  {
    id: '4',
    job_offer_id: '1',
    first_name: 'Sarah',
    last_name: 'Williams',
    email: 'sarah.w@email.com',
    phone: '+1 555-0104',
    cv_url: null,
    status: 'OFFER',
    interview_date: null,
    notes: 'Excellent fit for the team',
    created_at: '2024-11-28',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalEmployees: 75,
  presentToday: 62,
  lateToday: 5,
  onLeave: 8,
  pendingRequests: 12,
  openPositions: 4,
  newCandidates: 15,
};

export const mockNotifications: Notification[] = [
  {
    id: '1',
    user_id: '2',
    title: 'New Vacation Request',
    message: 'Emily Chen requested 5 days of vacation',
    type: 'INFO',
    is_read: false,
    link: '/vacation',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '2',
    user_id: '2',
    title: 'Task Completed',
    message: 'Prepare Training Materials has been completed',
    type: 'SUCCESS',
    is_read: false,
    link: '/tasks',
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: '3',
    user_id: '2',
    title: 'New Candidate Applied',
    message: 'Michael Johnson applied for HR Specialist position',
    type: 'INFO',
    is_read: true,
    link: '/recruitment',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];
